const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const path = require('path');
const NexusOrchestrator = require('./index');
const multer = require('multer');
const fs = require('fs');

const { db } = require('./core/firebase');
const ConfigService = require('./core/config');

const app = express();
const server = http.createServer(app);
const io = new Server(server);

// Parse JSON bodies for API routes
app.use(express.json());

// ─── Configuration Management API ─────────────────────────────────────
const CONFIG_KEY_LABELS = {
    GEMINI_API_KEY: 'Gemini API Key 1 (Primary)',
    GEMINI_API_KEY_2: 'Gemini API Key 2 (Backup)',
    GEMINI_API_KEY_3: 'Gemini API Key 3 (Backup)',
    BRAVE_SEARCH_API_KEY: 'Brave Search API Key (for Web Search)',
    GMAIL_USER: 'Gmail Address (for Email Tool)',
    GMAIL_APP_PASSWORD: 'Gmail App Password (for Email Tool)',
    WHATSAPP_PHONE_ID: 'WhatsApp Phone ID (from Meta Developer Portal)',
    META_ACCESS_TOKEN: 'Meta Access Token',
    META_AD_ACCOUNT_ID: 'Meta Ad Account ID',
    META_PAGE_ID: 'Meta Page ID',
    REPLICATE_API_TOKEN: 'Replicate API Token',
    OPENROUTER_API_TOKEN: 'OpenRouter API Token',
    LINKEDIN_ACCESS_TOKEN: 'LinkedIn Access Token',
    GOOGLE_ADS_CLIENT_ID: 'Google Ads Client ID',
    GOOGLE_ADS_CLIENT_SECRET: 'Google Ads Client Secret',
    GOOGLE_ADS_REFRESH_TOKEN: 'Google Ads Refresh Token',
    GOOGLE_ADS_DEVELOPER_TOKEN: 'Google Ads Developer Token',
    QUOTA_MODE: 'Performance Mode (FREE, NORMAL, HIGH)',
};

function maskValue(val) {
    if (!val || val.length < 8) return '••••••••';
    return val.substring(0, 4) + '••••••••' + val.substring(val.length - 4);
}

app.get('/api/config', async (req, res) => {
    try {
        if (!db) return res.status(503).json({ error: 'Firebase not initialized' });
        const doc = await db.collection('configs').doc('default').get();
        const data = doc.exists ? doc.data() : {};

        // Build response: all known keys, masked values, and flags
        const configs = Object.entries(CONFIG_KEY_LABELS).map(([key, label]) => ({
            key,
            label,
            value: data[key] ? maskValue(data[key]) : '',
            isSet: !!data[key],
        }));

        res.json({ configs });
    } catch (err) {
        console.error('[API] Config fetch error:', err.message);
        res.status(500).json({ error: err.message });
    }
});

app.post('/api/config', async (req, res) => {
    try {
        if (!db) return res.status(503).json({ error: 'Firebase not initialized' });
        const { updates } = req.body; // { KEY: 'value', ... }
        if (!updates || typeof updates !== 'object') {
            return res.status(400).json({ error: 'Invalid payload. Expected { updates: { KEY: value } }' });
        }

        // Filter out empty strings and masked placeholder values generated by the UI
        const cleanUpdates = {};
        for (const [key, value] of Object.entries(updates)) {
            if (value && value.trim() !== '' && !value.includes('••••')) {
                cleanUpdates[key] = value.trim();
            }
        }

        if (Object.keys(cleanUpdates).length === 0) {
            return res.status(400).json({ error: 'No values to update' });
        }

        await db.collection('configs').doc('default').set(cleanUpdates, { merge: true });
        ConfigService.refresh(); // Bust the cache immediately
        console.log(`[API] Config updated: ${Object.keys(cleanUpdates).join(', ')}`);
        res.json({ success: true, updatedKeys: Object.keys(cleanUpdates) });
    } catch (err) {
        console.error('[API] Config update error:', err.message);
        res.status(500).json({ error: err.message });
    }
});

app.get('/api/config/:key/raw', async (req, res) => {
    try {
        if (!db) return res.status(503).json({ error: 'Firebase not initialized' });
        const { key } = req.params;
        const doc = await db.collection('configs').doc('default').get();
        const data = doc.exists ? doc.data() : {};
        if (data[key]) {
            res.json({ value: data[key] });
        } else {
            res.status(404).json({ error: 'Key not found' });
        }
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

app.get('/api/system-status', async (req, res) => {
    try {
        let firestoreData = {};
        if (db) {
            const doc = await db.collection('configs').doc('default').get();
            firestoreData = doc.exists ? doc.data() : {};
        }

        const has = (key) => !!(firestoreData[key] || process.env[key]);

        const integrations = [
            {
                id: 'gemini_keys',
                name: 'Gemini (Auto-Key Rotation)',
                icon: '🔄',
                description: 'Key rotation active. Switches to backup keys on 429 errors.',
                status: has('GEMINI_API_KEY') ? 'active' : 'missing',
                keys: [
                    { key: 'GEMINI_API_KEY', label: 'Gemini Key 1', isSet: has('GEMINI_API_KEY') },
                    { key: 'GEMINI_API_KEY_2', label: 'Gemini Key 2', isSet: has('GEMINI_API_KEY_2') },
                    { key: 'GEMINI_API_KEY_3', label: 'Gemini Key 3', isSet: has('GEMINI_API_KEY_3') }
                ],
                howToGet: 'Get keys from https://aistudio.google.com/app/apikey',
                addVia: 'Settings → Gemini API Keys'
            },
            {
                id: 'search',
                name: 'Web Search (Brave)',
                icon: '🌐',
                description: 'Live web search for up-to-date information.',
                status: has('BRAVE_SEARCH_API_KEY') ? 'active' : 'missing',
                keys: [{ key: 'BRAVE_SEARCH_API_KEY', label: 'Brave Search Key', isSet: has('BRAVE_SEARCH_API_KEY') }],
                howToGet: 'Get a key from https://api.search.brave.com/',
                addVia: 'Settings → Brave Search API Key'
            },
            {
                id: 'email',
                name: 'Email (Gmail)',
                icon: '📧',
                description: 'Send and read client emails via Gmail SMTP/IMAP.',
                status: (has('GMAIL_USER') && has('GMAIL_APP_PASSWORD')) ? 'active' : 'missing',
                keys: [
                    { key: 'GMAIL_USER', label: 'Gmail Address', isSet: has('GMAIL_USER') },
                    { key: 'GMAIL_APP_PASSWORD', label: 'App Password', isSet: has('GMAIL_APP_PASSWORD') }
                ],
                howToGet: 'Google Account Settings → Security → 2FA → App Passwords',
                addVia: 'Settings → Gmail Credentials'
            },
            {
                id: 'whatsapp',
                name: 'WhatsApp Business',
                icon: '💬',
                description: 'Direct messaging via Meta WhatsApp Cloud API.',
                status: (has('WHATSAPP_PHONE_ID') && has('META_ACCESS_TOKEN')) ? 'active' : 'missing',
                keys: [
                    { key: 'WHATSAPP_PHONE_ID', label: 'Phone ID', isSet: has('WHATSAPP_PHONE_ID') },
                    { key: 'META_ACCESS_TOKEN', label: 'Access Token', isSet: has('META_ACCESS_TOKEN') }
                ],
                howToGet: 'Meta Developer Portal → WhatsApp Setup',
                addVia: 'Settings → Meta / WhatsApp Phone ID'
            },
            {
                id: 'memory',
                name: 'Long-Term Memory',
                icon: '🧠',
                description: 'Persistent fact storage across missions via Firestore.',
                status: db ? 'active' : 'missing',
                keys: [],
                howToGet: 'Auto-configured via Firestore.',
                addVia: 'No action needed'
            },
            {
                id: 'squad',
                name: 'Multi-Agent Squads',
                icon: '👥',
                description: 'Delegation to Researcher, Writer, Coder, Designer specialists.',
                status: 'active',
                keys: [],
                howToGet: 'Built-in capability.',
                addVia: 'No action needed'
            },
            {
                id: 'code_intel',
                name: 'Code Intelligence',
                icon: '🔍',
                description: 'Deep codebase mapping, grep search, and function finding.',
                status: 'active',
                keys: [],
                howToGet: 'Native local capability.',
                addVia: 'No action needed'
            },
            {
                id: 'meta_ads',
                name: 'Meta Ads Manager',
                icon: '📊',
                description: 'Full campaign lifecycle management.',
                status: has('META_AD_ACCOUNT_ID') ? 'active' : 'missing',
                keys: [{ key: 'META_AD_ACCOUNT_ID', label: 'Ad Account ID', isSet: has('META_AD_ACCOUNT_ID') }],
                howToGet: 'Business Manager → Ad Account Settings',
                addVia: 'Settings'
            }
        ];

        res.json({ integrations });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// ─── CRM & Agency Portal API ───────────────────────────────────────────
app.get('/api/clients', async (req, res) => {
    try {
        if (!db) return res.status(503).json({ error: 'Firebase not initialized' });
        const snapshot = await db.collection('clients').orderBy('createdAt', 'desc').get();
        const clients = [];
        snapshot.forEach(doc => clients.push({ id: doc.id, ...doc.data() }));
        res.json({ clients });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

app.post('/api/clients', async (req, res) => {
    try {
        if (!db) return res.status(503).json({ error: 'Firebase not initialized' });
        const { name, email, phone, company, notes } = req.body;
        const docRef = await db.collection('clients').add({
            name, email, phone, company, notes: notes || '',
            createdAt: new Date(),
            status: 'active'
        });
        res.json({ success: true, id: docRef.id });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

app.get('/api/projects', async (req, res) => {
    try {
        if (!db) return res.status(503).json({ error: 'Firebase not initialized' });
        const snapshot = await db.collection('projects').orderBy('deadline', 'asc').get();
        const projects = [];
        snapshot.forEach(doc => projects.push({ id: doc.id, ...doc.data() }));
        res.json({ projects });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

app.post('/api/projects', async (req, res) => {
    try {
        if (!db) return res.status(503).json({ error: 'Firebase not initialized' });
        const { clientId, title, description, deadline, budget } = req.body;
        const docRef = await db.collection('projects').add({
            clientId, title, description, deadline: new Date(deadline), budget,
            status: 'in-progress',
            createdAt: new Date()
        });
        res.json({ success: true, id: docRef.id });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// ─── Per-Client API Keys Management ────────────────────────────────────
const CLIENT_KEY_LABELS = {
    META_ACCESS_TOKEN: 'Meta Access Token',
    META_AD_ACCOUNT_ID: 'Meta Ad Account ID',
    META_PAGE_ID: 'Meta Page ID',
    WHATSAPP_PHONE_ID: 'WhatsApp Phone ID',
    GOOGLE_ADS_CLIENT_ID: 'Google Ads Client ID',
    GOOGLE_ADS_CLIENT_SECRET: 'Google Ads Client Secret',
    GOOGLE_ADS_REFRESH_TOKEN: 'Google Ads Refresh Token',
    GOOGLE_ADS_DEVELOPER_TOKEN: 'Google Ads Developer Token',
    LINKEDIN_ACCESS_TOKEN: 'LinkedIn Access Token',
    GMAIL_USER: 'Gmail Address',
    GMAIL_APP_PASSWORD: 'Gmail App Password',
    CUSTOM_API_KEY_1: 'Custom API Key 1',
    CUSTOM_API_KEY_2: 'Custom API Key 2',
};

app.get('/api/clients/:id/keys', async (req, res) => {
    try {
        if (!db) return res.status(503).json({ error: 'Firebase not initialized' });
        const { id } = req.params;
        const doc = await db.collection('client_configs').doc(id).get();
        const data = doc.exists ? doc.data() : {};

        const keys = Object.entries(CLIENT_KEY_LABELS).map(([key, label]) => ({
            key,
            label,
            value: data[key] ? maskValue(data[key]) : '',
            isSet: !!data[key],
        }));

        res.json({ keys });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

app.post('/api/clients/:id/keys', async (req, res) => {
    try {
        if (!db) return res.status(503).json({ error: 'Firebase not initialized' });
        const { id } = req.params;
        const { updates } = req.body;
        if (!updates || typeof updates !== 'object') {
            return res.status(400).json({ error: 'Invalid payload' });
        }

        const cleanUpdates = {};
        for (const [key, value] of Object.entries(updates)) {
            if (value && value.trim() !== '' && !value.includes('••••')) {
                cleanUpdates[key] = value.trim();
            }
        }

        if (Object.keys(cleanUpdates).length === 0) {
            return res.status(400).json({ error: 'No values to update' });
        }

        await db.collection('client_configs').doc(id).set(cleanUpdates, { merge: true });
        console.log(`[API] Client ${id} keys updated: ${Object.keys(cleanUpdates).join(', ')}`);
        res.json({ success: true, updatedKeys: Object.keys(cleanUpdates) });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

app.get('/api/clients/:id/keys/:key/raw', async (req, res) => {
    try {
        if (!db) return res.status(503).json({ error: 'Firebase not initialized' });
        const { id, key } = req.params;
        const doc = await db.collection('client_configs').doc(id).get();
        const data = doc.exists ? doc.data() : {};
        if (data[key]) {
            res.json({ value: data[key] });
        } else {
            res.status(404).json({ error: 'Key not found' });
        }
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

app.put('/api/clients/:id', async (req, res) => {
    try {
        if (!db) return res.status(503).json({ error: 'Firebase not initialized' });
        const { id } = req.params;
        const { name, email, phone, company, notes } = req.body;
        await db.collection('clients').doc(id).update({
            name, email, phone, company, notes,
            updatedAt: new Date()
        });
        res.json({ success: true });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

app.delete('/api/clients/:id', async (req, res) => {
    try {
        if (!db) return res.status(503).json({ error: 'Firebase not initialized' });
        const { id } = req.params;
        await db.collection('clients').doc(id).delete();
        // Also delete client-specific config
        await db.collection('client_configs').doc(id).delete();
        res.json({ success: true });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Configure multer for file uploads
const uploadDir = path.join(__dirname, 'uploads');
if (!fs.existsSync(uploadDir)) {
    fs.mkdirSync(uploadDir, { recursive: true });
}

const storage = multer.diskStorage({
    destination: (req, file, cb) => {
        cb(null, uploadDir);
    },
    filename: (req, file, cb) => {
        // Keep original name but add timestamp to avoid collisions
        const timestamp = Date.now();
        cb(null, `${timestamp}-${file.originalname}`);
    }
});

const upload = multer({ storage: storage });

// Serve static files from the build directory
app.use(express.static(path.join(__dirname, 'frontend', 'dist')));

// Expose the uploads directory (optional, but good for verification if needed)
app.use('/uploads', express.static(uploadDir));

// File upload endpoint
app.post('/upload', (req, res, next) => {
    console.log(`[Upload] Received POST request to /upload`);
    next();
}, upload.single('file'), (req, res) => {
    if (!req.file) {
        console.log(`[Upload] No file in request`);
        return res.status(400).send({ error: 'No file uploaded' });
    }
    const filePath = path.join(uploadDir, req.file.filename);
    console.log(`[Upload] File saved to: ${filePath}`);
    res.send({ 
        message: 'File uploaded successfully', 
        filename: req.file.filename,
        originalName: req.file.originalname,
        path: filePath 
    });
});

// Expose the outputs directory so users can download generated files
app.use('/outputs', (req, res, next) => {
    console.log(`[Static] Output requested: ${req.url}`);
    // Force download if requested via query param or if it's a non-previewable file
    if (req.query.download) {
        res.setHeader('Content-Disposition', 'attachment');
    }
    next();
}, express.static(path.join(__dirname, 'outputs'), {
    maxAge: '1d'
}));

// Explicit wildcard route for SPA client-side routing and fallback
// Use a regex to bypass path-to-regexp syntax issues in Express 5
app.get(/.*/, (req, res, next) => {
    if (req.path === '/sessions') {
        const files = fs.readdirSync(sessionsBaseDir);
        const sessions = files.map(f => {
            const content = JSON.parse(fs.readFileSync(path.join(sessionsBaseDir, f), 'utf8'));
            return {
                id: content.sessionId,
                lastUpdated: content.lastUpdated,
                preview: content.chatHistory?.[1]?.text?.substring(0, 50) || 'New Mission'
            };
        }).sort((a, b) => new Date(b.lastUpdated) - new Date(a.lastUpdated));
        return res.send(sessions);
    }
    next();
});

app.get(/.*/, (req, res) => {
    res.sendFile(path.join(__dirname, 'frontend', 'dist', 'index.html'));
});

const sessionsBaseDir = path.join(__dirname, 'sessions');
if (!fs.existsSync(sessionsBaseDir)) fs.mkdirSync(sessionsBaseDir, { recursive: true });

io.on('connection', (socket) => {
    console.log('User connected to Web UI');
    let orchestrator = null;
    let sessionDir = null;
    let sessionId = null;

    socket.on('join_session', (data) => {
        sessionId = data.sessionId || `session_${Date.now()}`;
        const sessionMetaFile = path.join(sessionsBaseDir, `${sessionId}.json`);
        let savedState = null;

        if (fs.existsSync(sessionMetaFile)) {
            console.log(`[Session] Resuming persistent session: ${sessionId}`);
            savedState = JSON.parse(fs.readFileSync(sessionMetaFile, 'utf8'));
            sessionDir = savedState.sessionDir;
        }

        if (!sessionDir) {
            const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
            sessionDir = path.join(__dirname, 'outputs', `session_${timestamp}`);
        }

        if (!fs.existsSync(sessionDir)) fs.mkdirSync(sessionDir, { recursive: true });

        orchestrator = new NexusOrchestrator((logEvent) => {
            socket.emit('nexus_log', logEvent);
            // Auto-save on every log event to ensure persistence
            saveSession();
        }, sessionDir);

        if (savedState) {
            orchestrator.restorePersistentState(savedState.orchestratorState);
            socket.emit('session_recovered', { 
                sessionId, 
                history: savedState.chatHistory || [],
                logs: savedState.logs || []
            });
        } else {
            socket.emit('session_created', { sessionId });
        }
        
        updateOutputsList();
    });

    const saveSession = () => {
        if (!sessionId || !orchestrator) return;
        const sessionMetaFile = path.join(sessionsBaseDir, `${sessionId}.json`);
        // We'll need to capture the chat history and logs from the frontend or track them here.
        // For now, let's at least save the orchestrator internal state.
        const state = {
            sessionId,
            sessionDir,
            orchestratorState: orchestrator.getPersistentState(),
            // history and logs should be sent by client periodically or tracked by server
            lastUpdated: new Date().toISOString()
        };
        fs.writeFileSync(sessionMetaFile, JSON.stringify(state, null, 2));
    };

    socket.on('start_task', async (data) => {
        const { prompt, clientId } = data;
        if (!orchestrator) {
            socket.emit('nexus_log', { type: 'error', message: 'Nexus Orchestrator not initialized. Please refresh or start a new mission.' });
            return;
        }
        console.log(`Received task: ${prompt} | Client: ${clientId || 'None'}`);
        try {
            // Context Switching Phase
            if (clientId) {
                const doc = await db.collection('client_configs').doc(clientId).get();
                const clientConfigs = doc.exists ? doc.data() : {};
                orchestrator.setClientContext(clientId, clientConfigs);
            } else {
                orchestrator.setClientContext(null, {}); // Revert to global config
            }

            await orchestrator.execute(prompt);
            updateOutputsList();
            saveSession();
        } catch (error) {
            socket.emit('nexus_log', { type: 'error', message: `Orchestrator Error: ${error.message}` });
        }
    });

    socket.on('user_input', async (data) => {
        const { prompt, clientId } = data;
        if (!orchestrator) {
            socket.emit('nexus_log', { type: 'error', message: 'Nexus Orchestrator not initialized.' });
            return;
        }
        try {
            // Context Switching Phase
            if (clientId) {
                const doc = await db.collection('client_configs').doc(clientId).get();
                const clientConfigs = doc.exists ? doc.data() : {};
                orchestrator.setClientContext(clientId, clientConfigs);
            }

            await orchestrator.execute(prompt); // Use execute instead of resume to trigger the run loop with rules
            // Wait, resume is used specifically for tool input.
            // Let's keep resume but make sure resume handles context.
            await orchestrator.resume(prompt);
            updateOutputsList();
            saveSession();
        } catch (error) {
            socket.emit('nexus_log', { type: 'error', message: `Orchestrator Error: ${error.message}` });
        }
    });

    socket.on('sync_history', (data) => {
        // Client sends full history for deep persistence
        if (!sessionId) return;
        const sessionMetaFile = path.join(sessionsBaseDir, `${sessionId}.json`);
        if (fs.existsSync(sessionMetaFile)) {
            const state = JSON.parse(fs.readFileSync(sessionMetaFile, 'utf8'));
            state.chatHistory = data.history;
            state.logs = data.logs;
            fs.writeFileSync(sessionMetaFile, JSON.stringify(state, null, 2));
        }
    });

    const updateOutputsList = () => {
        if (fs.existsSync(sessionDir)) {
            const files = fs.readdirSync(sessionDir);
            const folderName = path.basename(sessionDir);
            socket.emit('outputs_list', {
                files: files.map(f => ({ name: f, url: `/outputs/${folderName}/${f}` }))
            });
        }
    };

    socket.on('get_outputs', updateOutputsList);

    socket.on('disconnect', () => {
        console.log('User disconnected');
    });
});

const PORT = process.env.PORT || 3000;
server.listen(PORT, () => {
    console.log(`Nexus OS Web Interface running on http://localhost:${PORT}`);
});
