require('dotenv').config();
const { GoogleGenAI } = require('@google/genai');
const fs = require('fs');
const path = require('path');

/**
 * Nexus OS: Image Generation Tool
 * Uses Google's Imagen via the @google/genai SDK.
 */
class ImageGenTool {
    constructor() {
        const apiKey = process.env.GEMINI_API_KEY;
        if (!apiKey) {
            throw new Error("GEMINI_API_KEY is not set in the environment.");
        }
        this.ai = new GoogleGenAI({ apiKey: apiKey });
        // Use Imagen 4 (adjust if needed)
        this.modelName = 'imagen-4.0-generate-001';
    }

    /**
     * Generates an image and saves it to the specified path.
     * @param {string} prompt - The text description of the image.
     * @param {string} savePath - The absolute path where the image should be saved.
     */
    async generateImage(prompt, savePath) {
        try {
            console.log(`[ImageGen] Generating image for prompt: "${prompt}"...`);

            const response = await this.ai.models.generateImages({
                model: this.modelName,
                prompt: prompt,
                parameters: {
                    sampleCount: 1,
                    aspectRatio: "1:1",
                    outputMimeType: "image/png"
                }
            });

            // Handle the deeply nested Imagen 4 response structure
            let imageData = null;

            // Try standard locations first
            if (response.images && response.images[0]) {
                imageData = response.images[0].imageBytes || response.images[0].bytes;
            } else if (response.generatedImages && response.generatedImages[0]) {
                const imgObj = response.generatedImages[0].image;
                if (imgObj && imgObj.imageBytes) {
                    imageData = imgObj.imageBytes;
                } else if (imgObj && imgObj.bytes) {
                    imageData = imgObj.bytes;
                }
            } else if (response.pageInternal && response.pageInternal[0]) {
                const page = response.pageInternal[0];
                if (page.image && page.image.bytes) {
                    imageData = page.image.bytes;
                } else if (page.images && page.images[0]) {
                    imageData = page.images[0].bytes;
                }
            }

            // Fallback for deeply nested sdkHttpResponseInternal (observed in debug logs)
            if (!imageData && response.sdkHttpResponseInternal && response.sdkHttpResponseInternal.contents) {
                try {
                    const contents = JSON.parse(response.sdkHttpResponseInternal.contents);
                    if (contents.predictions && contents.predictions[0] && contents.predictions[0].bytesBase64Encoded) {
                        imageData = contents.predictions[0].bytesBase64Encoded;
                    }
                } catch (e) {
                    console.error("[ImageGen] Failed to parse internal contents:", e);
                }
            }

            if (!imageData) {
                console.error("[ImageGen] Full Response Structure:", Object.keys(response));
                throw new Error("No images were generated by the API.");
            }

            // Ensure directory exists
            const dir = path.dirname(savePath);
            if (!fs.existsSync(dir)) {
                fs.mkdirSync(dir, { recursive: true });
            }

            fs.writeFileSync(savePath, Buffer.from(imageData, 'base64'));
            console.log(`[ImageGen] Image saved successfully to: ${savePath}`);
            return `Success: Image generated and saved to ${savePath}`;

        } catch (error) {
            console.error("[ImageGen Error]", error);
            return `Error generating image: ${error.message}`;
        }
    }
}

module.exports = new ImageGenTool();
